version: '3.8'

services:
  jenkins:
    container_name: jenkins-homelab
    build: .
    image: jenkins/newman
    restart: always
    privileged: true
    hostname: jenkinshomelab
    user: root
    labels:
      com.example.description: "Jenkins Server"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - qualitygate
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
networks:
  qualitygate:

